# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=too-many-lines
# pylint: disable=too-many-statements

import os

from azure.cli.core.aaz import AAZStrArg
from knack.log import get_logger

from .aaz.latest.aro.hcp.cluster._create import Create as _ClusterCreate
from .aaz.latest.aro.hcp.cluster._request_admin_credential import RequestAdminCredential as _RequestAdminCredential

logger = get_logger(__name__)


class ClusterCreate(_ClusterCreate):

    class HcpOpenShiftClustersCreateOrUpdate(_ClusterCreate.HcpOpenShiftClustersCreateOrUpdate):

        @property
        def content(self):
            _content = super().content
            if _content and "identity" in _content:
                _content["identity"]["type"] = "UserAssigned"
            elif _content:
                _content["identity"] = {"type": "UserAssigned"}
            return _content


class RequestAdminCredential(_RequestAdminCredential):

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        args_schema = super()._build_arguments_schema(*args, **kwargs)
        args_schema.file = AAZStrArg(
            options=["-f", "--file"],
            help="Path to write the kubeconfig to. If not specified, the kubeconfig is printed to stdout.",
            required=False,
        )
        return args_schema

    def _handler(self, command_args):
        lro_poller = super()._handler(command_args)
        lro_poller._result_callback = self._output
        return lro_poller

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True, secret_hidden=False)
        if result and "kubeconfig" in result:
            result["kubeconfig"] = result["kubeconfig"].replace("\\n", "\n")
            file_path = self.ctx.args.file.to_serialized_data() if hasattr(self.ctx.args, "file") and self.ctx.args.file else None
            if file_path:
                file_path = os.path.expanduser(file_path)
                with open(file_path, "w") as f:
                    f.write(result["kubeconfig"])
                logger.warning("Kubeconfig written to %s", file_path)
                return None
        return result
